export {default as Dashboard} from './dashboard'
export {default as Students} from './students'
export {default as Layout} from './layout'
export {default as Login} from './login'
export {default as Pertanyaan} from './pertanyaan'
export {default as Quiz} from './quiz'